title: C++ 动态新闻推送
description: 每周日推送从reddit/hackernews/lobsters以及众多英文博客中摘抄一些c++动态
baseurl: "/cppweeklynews"
url: "https://wanghenshui.github.io/"
theme: minima
markdown: kramdown
minima:
  date_format: ""
plugins:
  - jekyll-feed
  - jekyll-seo-tag
