exclude:
  - node_modules
  - script
  - posts/template.md

sass:
  style: :compressed
baseurl:
theme: jekyll-theme-primer
name: C++ 动态新闻推送
description: 每周更新c++相关信息
url: https://wanghenshui.github.io/cppweeklynews

plugins:
  - jekyll-feed
